name: Server Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: ssh connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ secrets.PATH }}
            git pull origin master
            npm i
            pm2 restart server-prod.js
            exit
