name: Server Deploy
on:
  push:
    branches: [master]

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: ssh connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_PASSWORD }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 22
          script: |
            cd /var/www/finikers-radio
            # git pull
            mkdir test
            exit
